version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: finnhub-zookeeper
    ports:
      - "7081:7081"
    environment:
      ZOOKEEPER_CLIENT_PORT: "7081"
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ['CMD','bash','-c',"ruok | nc localhost 7081"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finnhubnetwork

  broker:
    image: confluentinc/cp-server:7.4.0
    hostname: broker
    container_name: finnhub-broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "7071:7071"
      - "7072:7072"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:7081'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:7074,PLAINTEXT_HOST://localhost:7071
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 7072
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:7073
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:7074
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

    networks:
      - finnhubnetwork
    healthcheck:
      test: ['CMD','bash','-c',"nc -z localhost 7071"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    image: bitnami/spark:latest
    container_name: finnhub-spark-master
    volumes:
      - ./scripts:/opt/bitnami/spark/scripts
      - .requirements.txt:/opt/bitnami/spark/requirements.txt
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7075:7075"
      - "7076:7076"
    networks:
      - finnhubnetwork
networks:
  finnhubnetwork:
